from __future__ import annotations

import ctypes
import ipaddress
import json
import os
import shutil
import subprocess
import tempfile
import time
from pathlib import Path
from typing import Any

from .constants import DNS_PRESETS, HOSTS_BACKUP_PATH, STATE_PATH
from .domains import unique_domains
from .models import AppSettings, FilterResult

START_MARKER = "# >>> WEBSITE BLOCKER MANAGED RULES >>>"
END_MARKER = "# <<< WEBSITE BLOCKER MANAGED RULES <<<"


def is_windows_admin() -> bool:
    if os.name != "nt":
        return False
    try:
        return bool(ctypes.windll.shell32.IsUserAnAdmin())
    except (AttributeError, OSError):
        return False


def render_hosts_content(original: str, blocked: list[str], allowed: list[str]) -> str:
    """Render Website Blocker's bounded hosts section without touching unrelated entries."""
    start = original.find(START_MARKER)
    end = original.find(END_MARKER)
    if start >= 0 and end >= start:
        end += len(END_MARKER)
        original = original[:start].rstrip() + "\n" + original[end:].lstrip("\r\n")

    allowed_set = set(unique_domains(allowed))
    domains = [domain for domain in unique_domains(blocked) if domain not in allowed_set]
    if not domains:
        return original.rstrip() + "\n"

    lines = [START_MARKER, "# Generated by Website Blocker. Changes inside this section are replaced."]
    for domain in domains:
        lines.append(f"0.0.0.0 {domain}")
        lines.append(f"0.0.0.0 www.{domain}")
    lines.append(END_MARKER)
    return original.rstrip() + "\n\n" + "\n".join(lines) + "\n"


class SystemFilter:
    """Applies reversible DNS and hosts changes after an explicit user action."""

    def __init__(
        self,
        state_path: Path = STATE_PATH,
        hosts_path: Path | None = None,
        hosts_backup_path: Path = HOSTS_BACKUP_PATH,
    ):
        self.state_path = state_path
        system_root = Path(os.environ.get("SystemRoot", r"C:\Windows"))
        self.hosts_path = hosts_path or system_root / "System32" / "drivers" / "etc" / "hosts"
        self.hosts_backup_path = hosts_backup_path

    def _run_powershell(self, script: str, timeout: int = 15) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            ["powershell.exe", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-Command", script],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=timeout,
            check=False,
            creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
        )

    def _dns_snapshot(self) -> list[dict[str, Any]]:
        script = (
            "$ErrorActionPreference='Stop'; "
            "$items = Get-NetAdapter | Where-Object {$_.Status -eq 'Up'} | ForEach-Object { "
            "$dns = Get-DnsClientServerAddress -InterfaceIndex $_.ifIndex -AddressFamily IPv4; "
            "[pscustomobject]@{InterfaceIndex=[int]$_.ifIndex; InterfaceAlias=[string]$_.Name; "
            "ServerAddresses=@($dns.ServerAddresses)} }; "
            "$items | ConvertTo-Json -Compress"
        )
        completed = self._run_powershell(script)
        if completed.returncode != 0:
            raise RuntimeError(completed.stderr.strip() or "Could not read current DNS settings")
        raw = completed.stdout.strip()
        if not raw:
            raise RuntimeError("No active network adapters were found")
        payload = json.loads(raw)
        items = payload if isinstance(payload, list) else [payload]
        validated: list[dict[str, Any]] = []
        for item in items:
            index = int(item["InterfaceIndex"])
            if index <= 0:
                continue
            servers = item.get("ServerAddresses") or []
            if isinstance(servers, str):
                servers = [servers]
            valid_servers: list[str] = []
            for server in servers:
                try:
                    valid_servers.append(str(ipaddress.ip_address(server)))
                except ValueError:
                    continue
            validated.append(
                {"interface_index": index, "interface_alias": str(item.get("InterfaceAlias", "")), "servers": valid_servers}
            )
        if not validated:
            raise RuntimeError("No usable network adapters were found")
        return validated

    def _save_state(self, snapshot: list[dict[str, Any]]) -> None:
        self.state_path.parent.mkdir(parents=True, exist_ok=True)
        payload = {"active": True, "dns_snapshot": snapshot}
        with tempfile.NamedTemporaryFile(
            mode="w", encoding="utf-8", dir=self.state_path.parent, prefix=".filter-state.", suffix=".tmp", delete=False
        ) as stream:
            json.dump(payload, stream, indent=2)
            temp_path = Path(stream.name)
        os.replace(temp_path, self.state_path)

    def _load_state(self) -> dict[str, Any]:
        if not self.state_path.exists():
            return {}
        try:
            with self.state_path.open("r", encoding="utf-8") as stream:
                payload = json.load(stream)
            return payload if isinstance(payload, dict) else {}
        except (OSError, json.JSONDecodeError):
            return {}

    def _write_hosts(self, blocked: list[str], allowed: list[str]) -> bool:
        """Update only Website Blocker's section while preserving the protected file's ACL.

        Windows and security software can briefly lock the hosts file. Retrying the
        in-place write avoids surfacing transient errors, while skipping a no-op
        prevents touching the protected file for users without personal rules.
        """
        original_bytes = self.hosts_path.read_bytes()
        original = original_bytes.decode("utf-8", errors="surrogateescape")
        has_managed_section = START_MARKER in original and END_MARKER in original
        allowed_set = set(unique_domains(allowed))
        effective_blocked = [domain for domain in unique_domains(blocked) if domain not in allowed_set]
        if not effective_blocked and not has_managed_section:
            return False

        updated = render_hosts_content(original, effective_blocked, allowed)
        updated_bytes = updated.encode("utf-8", errors="surrogateescape")
        if updated_bytes == original_bytes:
            return False

        if not self.hosts_backup_path.exists():
            self.hosts_backup_path.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(self.hosts_path, self.hosts_backup_path)

        delays = (0.0, 0.12, 0.3, 0.65)
        last_error: OSError | None = None
        for delay in delays:
            if delay:
                time.sleep(delay)
            try:
                with self.hosts_path.open("r+b", buffering=0) as stream:
                    stream.seek(0)
                    stream.write(updated_bytes)
                    stream.truncate()
                    os.fsync(stream.fileno())
                if self.hosts_path.read_bytes() != updated_bytes:
                    raise OSError("Windows did not persist the complete hosts-file update")
                return True
            except OSError as exc:
                last_error = exc
        raise last_error or OSError("The Windows hosts file could not be updated")

    def _apply_dns(self, primary: str, secondary: str, indexes: list[int]) -> None:
        for value in (primary, secondary):
            ipaddress.ip_address(value)
        if not indexes or any(index <= 0 for index in indexes):
            raise RuntimeError("Adapter validation failed")
        index_list = ",".join(str(index) for index in sorted(set(indexes)))
        script = (
            "$ErrorActionPreference='Stop'; "
            f"$indexes=@({index_list}); $servers=@('{primary}','{secondary}'); "
            "foreach($index in $indexes){ Set-DnsClientServerAddress -InterfaceIndex $index -ServerAddresses $servers }; "
            "Clear-DnsClientCache"
        )
        completed = self._run_powershell(script)
        if completed.returncode != 0:
            raise RuntimeError(completed.stderr.strip() or "Windows rejected the DNS change")

    def enable(self, settings: AppSettings) -> FilterResult:
        if not is_windows_admin():
            return FilterResult(False, "Administrator permission is required", "Restart Website Blocker as administrator to change system filtering.")
        profile = DNS_PRESETS.get(settings.active_profile, DNS_PRESETS["strong"])
        primary = settings.custom_dns_primary if settings.active_profile == "custom" else profile["primary"]
        secondary = settings.custom_dns_secondary if settings.active_profile == "custom" else profile["secondary"]
        try:
            if ipaddress.ip_address(primary).version != 4 or ipaddress.ip_address(secondary).version != 4:
                raise ValueError("The current Windows adapter integration requires IPv4 DNS addresses")
        except ValueError:
            return FilterResult(False, "The custom DNS addresses are invalid", "Enter two valid IPv4 addresses.")

        try:
            existing = self._load_state()
            snapshot = existing.get("dns_snapshot") if existing.get("active") else None
            if not snapshot:
                snapshot = self._dns_snapshot()
                self._save_state(snapshot)
            indexes = [int(item["interface_index"]) for item in snapshot]
            self._write_hosts(settings.blocked_domains, settings.allowed_domains)
            self._apply_dns(str(primary), str(secondary), indexes)
            return FilterResult(True, "Protection is active", f"Using {profile['provider']} across {len(indexes)} active adapter(s).")
        except (OSError, RuntimeError, ValueError, json.JSONDecodeError, subprocess.SubprocessError) as exc:
            return FilterResult(False, "Protection could not be enabled", str(exc))

    def disable(self) -> FilterResult:
        if not is_windows_admin():
            return FilterResult(False, "Administrator permission is required", "Restart Website Blocker as administrator to restore network settings.")
        state = self._load_state()
        snapshot = state.get("dns_snapshot", [])
        try:
            # Remove personal rules first. If the protected file is temporarily
            # unavailable, DNS stays filtered and the operation is safe to retry.
            self._write_hosts([], [])
            for item in snapshot:
                index = int(item["interface_index"])
                servers = [str(ipaddress.ip_address(value)) for value in item.get("servers", [])]
                if servers:
                    joined = ",".join(f"'{server}'" for server in servers)
                    command = (
                        "$ErrorActionPreference='Stop'; "
                        f"Set-DnsClientServerAddress -InterfaceIndex {index} -ServerAddresses @({joined})"
                    )
                else:
                    command = (
                        "$ErrorActionPreference='Stop'; "
                        f"Set-DnsClientServerAddress -InterfaceIndex {index} -ResetServerAddresses"
                    )
                completed = self._run_powershell(command)
                if completed.returncode != 0:
                    raise RuntimeError(completed.stderr.strip() or f"Could not restore adapter {index}")
            self._run_powershell("Clear-DnsClientCache")
            self.state_path.unlink(missing_ok=True)
            return FilterResult(True, "Protection is paused", "Your previous DNS settings were restored.")
        except (OSError, RuntimeError, ValueError, subprocess.SubprocessError) as exc:
            return FilterResult(False, "Network settings could not be restored", str(exc))


class PreviewSystemFilter(SystemFilter):
    """Non-mutating implementation used for screenshots and UI development."""

    def enable(self, settings: AppSettings) -> FilterResult:
        return FilterResult(True, "Preview protection is active", "No system settings were changed in preview mode.")

    def disable(self) -> FilterResult:
        return FilterResult(True, "Preview protection is paused", "No system settings were changed in preview mode.")
